Taller-Kforce-Autos/Taller-Kforce-Autos/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.Json.Serialization;
using System.Text.Json;
using Taller_Kforce_Autos.Models;
using System.Net.Http.Json;

namespace Taller_Kforce_Autos.Controllers
{
    public class CarController : Controller
    {
        private static List<Car> cars = new()
        {
            new Car { Id = 1, Make = "Audi", Model = "R8", Year = 2018, Doors = 2, Color = "Red", Price = 79995 },
            new Car { Id = 2, Make = "Tesla", Model = "3", Year = 2018, Doors = 4, Color = "Black", Price = 54995 },
            new Car { Id = 3, Make = "Porsche", Model = "911 991", Year = 2020, Doors = 2, Color = "White", Price = 155000 },
            new Car { Id = 4, Make = "Mercedes-Benz", Model = "GLE 63S", Year = 2021, Doors = 5, Color = "Blue", Price = 83995 },
            new Car { Id = 5, Make = "BMW", Model = "X6 M", Year = 2020, Doors = 5, Color = "Silver", Price = 62995 },
        };

        public IActionResult Index()
        {
            List<Car> orderedCars = cars.OrderBy(x => x.Id).ToList();
            return View(orderedCars);
        }

        public IActionResult CreateCar()
        {
            List<int> years = new List<int>();
            int currentYear = DateTime.Now.Year;

            for (int i = currentYear - 50; i <= currentYear; i++)
            {
                years.Add(i);
            }

            ViewBag.Years = new SelectList(years);

            return View();
        }

        public IActionResult EditCar(int id)
        {
            try
            {
                if (cars.Any(x => x.Id == id))
                {
                    Car car = cars.Select(c => new Car
                    {
                        Id = c.Id,
                        Make = c.Make,
                        Model = c.Model,
                        Year = c.Year,
                        Doors = c.Doors,
                        Color = c.Color,
                        Price = c.Price
                    }).First(x => x.Id == id);

                    return View(car);
                }
                else
                {
                    return RedirectToAction("Error", "Home");
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public IActionResult DeleteCar(int id)
        {
            try
            {
                if (cars.Any(x => x.Id == id))
                {
                    Car car = cars.Select(c => new Car
                    {
                        Id = c.Id,
                        Make = c.Make,
                        Model = c.Model,
                        Year = c.Year,
                        Doors = c.Doors,
                        Color = c.Color,
                        Price = c.Price
                    }).First(x => x.Id == id);

                    return View(car);
                }
                else
                {
                    return RedirectToAction("Error", "Home");
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(Car car)
        {
            try
            {
                //List<Car> cars =new List<Car> { car };
                List<Car> orderedCars = cars.OrderBy(x => x.Id).ToList();
                var lastCar = orderedCars.LastOrDefault();
                car.Id = lastCar.Id + 1;
                cars.Add(car);
                return base.RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Update(Car car)
        {
            try
            {
                var carUpdate = cars.FirstOrDefault(x => x.Id == car.Id);
                if (carUpdate != null)
                {
                    carUpdate.Make = car.Make;
                    carUpdate.Model = car.Model;
                    carUpdate.Year = car.Year;
                    carUpdate.Doors = car.Doors;
                    carUpdate.Color = car.Color;
                    carUpdate.Price = car.Price;

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction("Error", "Home");
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                if (cars.Any(x => x.Id == id))
                {
                    Car carDelete = cars.FirstOrDefault(x => x.Id == id);
                    cars.Remove(carDelete);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction("Error", "Home");
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }
        }

        public async Task<IActionResult> Cancel()
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

Taller-Kforce-Autos/Taller-Kforce-Autos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Taller_Kforce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Taller_Kforce_Autos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Taller_Kforce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index">Cars</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Game</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Taller_Kforce_Autos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>